function settings = vk_4dgui_state_from_vardata(vardata)
    settings = { ...
        'labels', char(vardata(:,1)), ...
        'symbols', char(vardata(:, 2)), ...
        'constraint_set', ...
            reshape(transpose(cell2mat(vardata(:, 3:4))), 1, []), ...
        'diff_eqn', char(vardata(:, 5))};
end