%% VK_PROJECT_FROM_VARDATA Returns a skeleton project from a cell array
function project = vk_project_from_vardata(vardata)
    project = { ...
        'vardata', {vardata}, ...
        'labels', char(vardata(:,1)), ...
        'symbols', char(vardata(:, 2)), ...
        'K', ...
            reshape(transpose(cell2mat(vardata(:, 3:4))), 1, []), ...
        'diff_eqns', char(vardata(:, 5))};
end